name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todo_list_kadince_test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.3.2'

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Setup Database
        env:
          RAILS_ENV: test
        run: |
          mkdir -p config
          cp .github/config/database.yml.github_actions config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run Tests
        run: |
          bundle exec rails test

      - name: Deploy to Heroku
        if: success()
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/todo-list-app.git
          git push heroku main -f
